"""
Write a function to compute 5/0 and use try/except to catch the exceptions.

Hints:

Use try/except to catch exceptions.
"""

try:
    result = 5 / 0
except:
    print('Compute by 0!')
